{% set name = "scikit-hep-testdata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-hep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4dda00d021fc18d78e89063604446f12fd773735224c2001b5b4fd9fca2b43fd

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python
    - pyyaml
    - importlib_resources

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - skhep_testdata
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/scikit-hep/scikit-hep-testdata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Example HEP files for testing and demonstrating
  doc_url: https://github.com/scikit-hep/scikit-hep-testdata#installing-and-usage
  dev_url: https://github.com/scikit-hep/scikit-hep-testdata/

extra:
  recipe-maintainers:
    - chrisburr
